name: Docker build
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/metadata-action@v4.3.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Kaniko build
        uses: int128/kaniko-action@v1
        with:
          push: false
          context: base
          build-args: 
            - "RUBY_VERSION=2.6.9"
